export const CREATE_INCOME_BUDGETS = 'CREATE_INCOME_BUDGETS';
export const LIST_INCOME_BUDGETS = 'LIST_INCOME_BUDGETS';
export const DELETE_INCOME_BUDGET = 'DELETE_INCOME_BUDGET';
export const EDIT_INCOME_BUDGET = 'EDIT_INCOME_BUDGET';

export const CREATE_EXPENSES_BUDGETS = 'CREATE_EXPENSES_BUDGETS';
export const LIST_EXPENSES_BUDGETS = 'LIST_EXPENSES_BUDGETS';
export const DELETE_EXPENSES_BUDGET = 'DELETE_EXPENSES_BUDGET';
export const EDIT_EXPENSES_BUDGET = 'EDIT_EXPENSES_BUDGET';

export const CREATE_NOTE = 'CREATE_NOTE';
export const READ_NOTE = 'READ_NOTE';
export const UPDATE_NOTE =  'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const GET_NOTES = 'GET_NOTES';
export const GET_NOTE = 'GET_NOTE';
export const LIKE_NOTE = 'LIKE_NOTE';
export const UNLIKE_NOTE = 'UNLIKE_NOTE';
export const COMMENTS_NOTE = 'COMMENTS_NOTE';
export const FRIENDS_NOTE = 'FRIENDS_NOTE';

export const CREATE_TODO = 'CREATE_TODO';
export const UPDATE_TODO =  'UPDATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const LIST_TODOS = 'LIST_TODOS';

export const GET_USER = 'GET_USER';
export const GET_AUTH_USER = 'GET_AUTH_USER';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
